import {
  CONFIRM_EMAIL_CHANGE_ROUTE_PATH,
  FORGOT_PASSWORD_ROUTE_PATH,
  RESET_PASSWORD_ROUTE_PATH,
  RESET_PASSWORD_VALIDATE_ROUTE_PATH,
  SIGN_IN_ROUTE_PATH,
  SIGN_UP_ROUTE_PATH,
} from "@pacetrack/schema";

export const PUBLIC_API_ROUTES = [
  "/api/healthcheck",
  SIGN_IN_ROUTE_PATH,
  SIGN_UP_ROUTE_PATH,
  FORGOT_PASSWORD_ROUTE_PATH,
  RESET_PASSWORD_ROUTE_PATH,
  RESET_PASSWORD_VALIDATE_ROUTE_PATH,
  CONFIRM_EMAIL_CHANGE_ROUTE_PATH,
];

export const PUBLIC_WEB_ROUTES = [
  "/auth",
  "/auth/sign-in",
  "/auth/sign-up",
  "/auth/forgot-password",
];
