/** biome-ignore-all assist/source/organizeImports: We don't want this for this file */

// Auto-generated by scripts/generate-route-definitions.ts
// Do not edit manually

import { ACCOUNT_ACCEPT_INVITE_ROUTE } from "./acount/account.accept-invite.types";
import { ACCOUNT_CHANGE_EMAIL_ROUTE } from "./acount/account.change-email.types";
import { ACCOUNT_CONFIRM_EMAIL_CHANGE_ROUTE } from "./acount/account.confirm-email-change.types";
import { ACCOUNT_DELETE_ROUTE } from "./acount/account.delete.types";
import { ACCOUNT_GET_BY_ID_ROUTE } from "./acount/account.get-by-id.types";
import { ACCOUNT_GET_ROLES_ROUTE } from "./acount/account.get-roles.types";
import { ACCOUNT_GET_ROUTE } from "./acount/account.get.types";
import { ACCOUNT_GROUP_ADD_ACCOUNTS_ROUTE } from "./account-group/account-group.add-users.types";
import { ACCOUNT_GROUP_CREATE_ROUTE } from "./account-group/account-group.create.types";
import { ACCOUNT_GROUP_DELETE_ROUTE } from "./account-group/account-group.delete.types";
import { ACCOUNT_GROUP_GET_BY_ID_ROUTE } from "./account-group/account-group.get-by-id.types";
import { ACCOUNT_GROUP_GET_ROUTE } from "./account-group/account-group.get.types";
import { ACCOUNT_GROUP_REMOVE_ACCOUNTS_ROUTE } from "./account-group/account-group.remove-users.types";
import { ACCOUNT_GROUP_UPDATE_ROUTE } from "./account-group/account-group.update.types";
import { ACCOUNT_QUERY_ROUTE } from "./acount/account.query.types";
import { ACCOUNT_UPDATE_PASSWORD_ROUTE } from "./acount/account.update-password.types";
import { ACCOUNT_UPDATE_ROUTE } from "./acount/account.update.types";
import { FORGOT_PASSWORD_ROUTE } from "./auth/forgot-password.types";
import { MEMBERSHIP_CANCEL_ROUTE } from "./membership/membership.cancel.types";
import { MEMBERSHIP_CREATE_ROUTE } from "./membership/membership.create.types";
import { MEMBERSHIP_GET_ROUTE } from "./membership/membership.get.types";
import { MEMBERSHIP_PORTAL_LINK_ROUTE } from "./membership/membership.portal-link.types";
import { MEMBERSHIP_SWITCH_ROUTE } from "./membership/membership.switch.types";
import { RESET_PASSWORD_ROUTE } from "./auth/reset-password.types";
import { RESET_PASSWORD_VALIDATE_ROUTE } from "./auth/reset-password-validate.types";
import { SESSION_LIST_ROUTE } from "./session/session.list.types";
import { SESSION_REVOKE_ALL_ROUTE } from "./session/session.revoke-all.types";
import { SESSION_REVOKE_ROUTE } from "./session/session.revoke.types";
import { SESSION_SWITCH_ACCOUNT_ROUTE } from "./session/session.switch-account.types";
import { SESSION_SWITCH_TENANT_ROUTE } from "./session/session.switch-tenant.types";
import { SIGN_IN_ROUTE } from "./auth/sign-in.types";
import { SIGN_OUT_ROUTE } from "./auth/sign-out.types";
import { SIGN_UP_ROUTE } from "./auth/sign-up.types";
import { TENANT_CREATE_ROUTE } from "./tenant/tenant.create.types";
import { TENANT_DELETE_ROUTE } from "./tenant/tenant.delete.types";
import { TENANT_GET_BY_ID_ROUTE } from "./tenant/tenant.get-by-id.types";
import { TENANT_GET_ROUTE } from "./tenant/tenant.get.types";
import { TENANT_INVITE_USERS_ROUTE } from "./tenant/tenant.invite-users.types";
import { TENANT_UPDATE_ROUTE } from "./tenant/tenant.update.types";
import { USER_CREATE_ROUTE } from "./user/user.create.types";
import { USER_DELETE_ROUTE } from "./user/user.delete.types";
import { USER_GET_BY_ID_ROUTE } from "./user/user.get-by-id.types";
import { VALIDATE_SESSION_ROUTE } from "./session/session.validate";

export const ROUTE_DEFINITIONS = {
  ACCOUNT_ACCEPT_INVITE_ROUTE: ACCOUNT_ACCEPT_INVITE_ROUTE,
  ACCOUNT_CHANGE_EMAIL_ROUTE: ACCOUNT_CHANGE_EMAIL_ROUTE,
  ACCOUNT_CONFIRM_EMAIL_CHANGE_ROUTE: ACCOUNT_CONFIRM_EMAIL_CHANGE_ROUTE,
  ACCOUNT_DELETE_ROUTE: ACCOUNT_DELETE_ROUTE,
  ACCOUNT_GET_BY_ID_ROUTE: ACCOUNT_GET_BY_ID_ROUTE,
  ACCOUNT_GET_ROLES_ROUTE: ACCOUNT_GET_ROLES_ROUTE,
  ACCOUNT_GET_ROUTE: ACCOUNT_GET_ROUTE,
  ACCOUNT_GROUP_ADD_ACCOUNTS_ROUTE: ACCOUNT_GROUP_ADD_ACCOUNTS_ROUTE,
  ACCOUNT_GROUP_CREATE_ROUTE: ACCOUNT_GROUP_CREATE_ROUTE,
  ACCOUNT_GROUP_DELETE_ROUTE: ACCOUNT_GROUP_DELETE_ROUTE,
  ACCOUNT_GROUP_GET_BY_ID_ROUTE: ACCOUNT_GROUP_GET_BY_ID_ROUTE,
  ACCOUNT_GROUP_GET_ROUTE: ACCOUNT_GROUP_GET_ROUTE,
  ACCOUNT_GROUP_REMOVE_ACCOUNTS_ROUTE: ACCOUNT_GROUP_REMOVE_ACCOUNTS_ROUTE,
  ACCOUNT_GROUP_UPDATE_ROUTE: ACCOUNT_GROUP_UPDATE_ROUTE,
  ACCOUNT_QUERY_ROUTE: ACCOUNT_QUERY_ROUTE,
  ACCOUNT_UPDATE_PASSWORD_ROUTE: ACCOUNT_UPDATE_PASSWORD_ROUTE,
  ACCOUNT_UPDATE_ROUTE: ACCOUNT_UPDATE_ROUTE,
  FORGOT_PASSWORD_ROUTE: FORGOT_PASSWORD_ROUTE,
  MEMBERSHIP_CANCEL_ROUTE: MEMBERSHIP_CANCEL_ROUTE,
  MEMBERSHIP_CREATE_ROUTE: MEMBERSHIP_CREATE_ROUTE,
  MEMBERSHIP_GET_ROUTE: MEMBERSHIP_GET_ROUTE,
  MEMBERSHIP_PORTAL_LINK_ROUTE: MEMBERSHIP_PORTAL_LINK_ROUTE,
  MEMBERSHIP_SWITCH_ROUTE: MEMBERSHIP_SWITCH_ROUTE,
  RESET_PASSWORD_ROUTE: RESET_PASSWORD_ROUTE,
  RESET_PASSWORD_VALIDATE_ROUTE: RESET_PASSWORD_VALIDATE_ROUTE,
  SESSION_LIST_ROUTE: SESSION_LIST_ROUTE,
  SESSION_REVOKE_ALL_ROUTE: SESSION_REVOKE_ALL_ROUTE,
  SESSION_REVOKE_ROUTE: SESSION_REVOKE_ROUTE,
  SESSION_SWITCH_ACCOUNT_ROUTE: SESSION_SWITCH_ACCOUNT_ROUTE,
  SESSION_SWITCH_TENANT_ROUTE: SESSION_SWITCH_TENANT_ROUTE,
  SIGN_IN_ROUTE: SIGN_IN_ROUTE,
  SIGN_OUT_ROUTE: SIGN_OUT_ROUTE,
  SIGN_UP_ROUTE: SIGN_UP_ROUTE,
  TENANT_CREATE_ROUTE: TENANT_CREATE_ROUTE,
  TENANT_DELETE_ROUTE: TENANT_DELETE_ROUTE,
  TENANT_GET_BY_ID_ROUTE: TENANT_GET_BY_ID_ROUTE,
  TENANT_GET_ROUTE: TENANT_GET_ROUTE,
  TENANT_INVITE_USERS_ROUTE: TENANT_INVITE_USERS_ROUTE,
  TENANT_UPDATE_ROUTE: TENANT_UPDATE_ROUTE,
  USER_CREATE_ROUTE: USER_CREATE_ROUTE,
  USER_DELETE_ROUTE: USER_DELETE_ROUTE,
  USER_GET_BY_ID_ROUTE: USER_GET_BY_ID_ROUTE,
  VALIDATE_SESSION_ROUTE: VALIDATE_SESSION_ROUTE,
};
