/** biome-ignore-all assist/source/organizeImports: We don't want this for this file */

// Auto-generated by scripts/generate-route-definitions.ts
// Do not edit manually

import { ACCOUNT_ACCEPT_INVITE_ROUTE } from "./acount/account.accept-invite.types";
import { ACCOUNT_CHANGE_EMAIL_ROUTE } from "./acount/account.change-email.types";
import { ACCOUNT_CONFIRM_EMAIL_CHANGE_ROUTE } from "./acount/account.confirm-email-change.types";
import { ACCOUNT_CREATE_ROUTE } from "./acount/account.create.types";
import { ACCOUNT_DELETE_ROUTE } from "./acount/account.delete.types";
import { ACCOUNT_GET_BY_ID_ROUTE } from "./acount/account.get-by-id.types";
import { ACCOUNT_GET_ROLES_ROUTE } from "./acount/account.get-roles.types";
import { ACCOUNT_GET_ROUTE } from "./acount/account.get.types";
import { ACCOUNT_GROUP_ADD_ACCOUNTS_ROUTE } from "./account-group/account-group.add-users.types";
import { ACCOUNT_GROUP_CREATE_ROUTE } from "./account-group/account-group.create.types";
import { ACCOUNT_GROUP_DELETE_ROUTE } from "./account-group/account-group.delete.types";
import { ACCOUNT_GROUP_GET_BY_ID_ROUTE } from "./account-group/account-group.get-by-id.types";
import { ACCOUNT_GROUP_GET_ROUTE } from "./account-group/account-group.get.types";
import { ACCOUNT_GROUP_REMOVE_ACCOUNTS_ROUTE } from "./account-group/account-group.remove-users.types";
import { ACCOUNT_GROUP_UPDATE_ROUTE } from "./account-group/account-group.update.types";
import { ACCOUNT_LINK_ROUTE } from "./acount/account.link.types";
import { ACCOUNT_QUERY_ROUTE } from "./acount/account.query.types";
import { ACCOUNT_UPDATE_PASSWORD_ROUTE } from "./acount/account.update-password.types";
import { ACCOUNT_UPDATE_ROUTE } from "./acount/account.update.types";
import { FORGOT_PASSWORD_ROUTE } from "./auth/forgot-password.types";
import { ITEM_TEMPLATE_CREATE_ROUTE } from "./item-template/item-template.create.types";
import { ITEM_TEMPLATE_DELETE_ROUTE } from "./item-template/item-template.delete.types";
import { ITEM_TEMPLATE_GET_BY_ID_ROUTE } from "./item-template/item-template.get-by-id.types";
import { ITEM_TEMPLATE_UPDATE_ROUTE } from "./item-template/item-template.update.types";
import { PIPELINE_INSTANCE_CREATE_ROUTE } from "./pipeline-instance/pipeline-instance.create.types";
import { PIPELINE_INSTANCE_DELETE_ROUTE } from "./pipeline-instance/pipeline-instance.delete.types";
import { PIPELINE_INSTANCE_GET_BY_ID_ROUTE } from "./pipeline-instance/pipeline-instance.get-by-id.types";
import { PIPELINE_INSTANCE_GET_BY_TEMPLATE_ID_ROUTE } from "./pipeline-instance/pipeline-instance.get-by-template-id.types";
import { PIPELINE_INSTANCE_GET_ROUTE } from "./pipeline-instance/pipeline-instance.get.types";
import { PIPELINE_INSTANCE_UPDATE_ROUTE } from "./pipeline-instance/pipeline-instance.update.types";
import { PIPELINE_TEMPLATE_CREATE_ROUTE } from "./pipeline-template/pipeline-template.create.types";
import { PIPELINE_TEMPLATE_DELETE_ROUTE } from "./pipeline-template/pipeline-template.delete.types";
import { PIPELINE_TEMPLATE_GET_BY_ID_ROUTE } from "./pipeline-template/pipeline-template.get-by-id.types";
import { PIPELINE_TEMPLATE_GET_ROUTE } from "./pipeline-template/pipeline-template.get.types";
import { PIPELINE_TEMPLATE_UPDATE_ROUTE } from "./pipeline-template/pipeline-template.update.types";
import { RESET_PASSWORD_ROUTE } from "./auth/reset-password.types";
import { RESET_PASSWORD_VALIDATE_ROUTE } from "./auth/reset-password-validate.types";
import { SESSION_CREATE_ACCOUNT_ROUTE } from "./session/session.create-account.types";
import { SESSION_CREATE_TENANT_ROUTE } from "./session/session.create-tenant.types";
import { SESSION_GET_ACCOUNTS_META_ROUTE } from "./session/session.get-accounts-meta.types";
import { SESSION_LINK_ACCOUNT_ROUTE } from "./session/session.link-account.types";
import { SESSION_LIST_ROUTE } from "./session/session.list.types";
import { SESSION_REMOVE_ACCOUNT_ROUTE } from "./session/session.remove-account.types";
import { SESSION_REVOKE_ALL_ROUTE } from "./session/session.revoke-all.types";
import { SESSION_REVOKE_ROUTE } from "./session/session.revoke.types";
import { SESSION_SWITCH_ACCOUNT_ROUTE } from "./session/session.switch-account.types";
import { SESSION_SWITCH_TENANT_ROUTE } from "./session/session.switch-tenant.types";
import { SIGN_IN_ROUTE } from "./auth/sign-in.types";
import { SIGN_OUT_ROUTE } from "./auth/sign-out.types";
import { SIGN_UP_ROUTE } from "./auth/sign-up.types";
import { STEP_GET_ROUTE } from "./step/step.get.types";
import { STEP_TEMPLATE_CREATE_ROUTE } from "./step-template/step-template.create.types";
import { STEP_TEMPLATE_DELETE_ROUTE } from "./step-template/step-template.delete.types";
import { STEP_TEMPLATE_GET_BY_ID_ROUTE } from "./step-template/step-template.get-by-id.types";
import { STEP_TEMPLATE_GET_ROUTE } from "./step-template/step-template.get.types";
import { STEP_TEMPLATE_UPDATE_ROUTE } from "./step-template/step-template.update.types";
import { TENANT_CREATE_ROUTE } from "./tenant/tenant.create.types";
import { TENANT_DELETE_ROUTE } from "./tenant/tenant.delete.types";
import { TENANT_GET_BY_ID_ROUTE } from "./tenant/tenant.get-by-id.types";
import { TENANT_GET_ROUTE } from "./tenant/tenant.get.types";
import { TENANT_INVITE_USERS_ROUTE } from "./tenant/tenant.invite-users.types";
import { TENANT_UPDATE_ROUTE } from "./tenant/tenant.update.types";
import { USER_CREATE_ROUTE } from "./user/user.create.types";
import { USER_DELETE_ROUTE } from "./user/user.delete.types";
import { USER_GET_BY_ID_ROUTE } from "./user/user.get-by-id.types";
import { VALIDATE_SESSION_ROUTE } from "./session/session.validate";

export const ROUTE_DEFINITIONS = {
  ACCOUNT_ACCEPT_INVITE_ROUTE: ACCOUNT_ACCEPT_INVITE_ROUTE,
  ACCOUNT_CHANGE_EMAIL_ROUTE: ACCOUNT_CHANGE_EMAIL_ROUTE,
  ACCOUNT_CONFIRM_EMAIL_CHANGE_ROUTE: ACCOUNT_CONFIRM_EMAIL_CHANGE_ROUTE,
  ACCOUNT_CREATE_ROUTE: ACCOUNT_CREATE_ROUTE,
  ACCOUNT_DELETE_ROUTE: ACCOUNT_DELETE_ROUTE,
  ACCOUNT_GET_BY_ID_ROUTE: ACCOUNT_GET_BY_ID_ROUTE,
  ACCOUNT_GET_ROLES_ROUTE: ACCOUNT_GET_ROLES_ROUTE,
  ACCOUNT_GET_ROUTE: ACCOUNT_GET_ROUTE,
  ACCOUNT_GROUP_ADD_ACCOUNTS_ROUTE: ACCOUNT_GROUP_ADD_ACCOUNTS_ROUTE,
  ACCOUNT_GROUP_CREATE_ROUTE: ACCOUNT_GROUP_CREATE_ROUTE,
  ACCOUNT_GROUP_DELETE_ROUTE: ACCOUNT_GROUP_DELETE_ROUTE,
  ACCOUNT_GROUP_GET_BY_ID_ROUTE: ACCOUNT_GROUP_GET_BY_ID_ROUTE,
  ACCOUNT_GROUP_GET_ROUTE: ACCOUNT_GROUP_GET_ROUTE,
  ACCOUNT_GROUP_REMOVE_ACCOUNTS_ROUTE: ACCOUNT_GROUP_REMOVE_ACCOUNTS_ROUTE,
  ACCOUNT_GROUP_UPDATE_ROUTE: ACCOUNT_GROUP_UPDATE_ROUTE,
  ACCOUNT_LINK_ROUTE: ACCOUNT_LINK_ROUTE,
  ACCOUNT_QUERY_ROUTE: ACCOUNT_QUERY_ROUTE,
  ACCOUNT_UPDATE_PASSWORD_ROUTE: ACCOUNT_UPDATE_PASSWORD_ROUTE,
  ACCOUNT_UPDATE_ROUTE: ACCOUNT_UPDATE_ROUTE,
  FORGOT_PASSWORD_ROUTE: FORGOT_PASSWORD_ROUTE,
  ITEM_TEMPLATE_CREATE_ROUTE: ITEM_TEMPLATE_CREATE_ROUTE,
  ITEM_TEMPLATE_DELETE_ROUTE: ITEM_TEMPLATE_DELETE_ROUTE,
  ITEM_TEMPLATE_GET_BY_ID_ROUTE: ITEM_TEMPLATE_GET_BY_ID_ROUTE,
  ITEM_TEMPLATE_UPDATE_ROUTE: ITEM_TEMPLATE_UPDATE_ROUTE,
  PIPELINE_INSTANCE_CREATE_ROUTE: PIPELINE_INSTANCE_CREATE_ROUTE,
  PIPELINE_INSTANCE_DELETE_ROUTE: PIPELINE_INSTANCE_DELETE_ROUTE,
  PIPELINE_INSTANCE_GET_BY_ID_ROUTE: PIPELINE_INSTANCE_GET_BY_ID_ROUTE,
  PIPELINE_INSTANCE_GET_BY_TEMPLATE_ID_ROUTE: PIPELINE_INSTANCE_GET_BY_TEMPLATE_ID_ROUTE,
  PIPELINE_INSTANCE_GET_ROUTE: PIPELINE_INSTANCE_GET_ROUTE,
  PIPELINE_INSTANCE_UPDATE_ROUTE: PIPELINE_INSTANCE_UPDATE_ROUTE,
  PIPELINE_TEMPLATE_CREATE_ROUTE: PIPELINE_TEMPLATE_CREATE_ROUTE,
  PIPELINE_TEMPLATE_DELETE_ROUTE: PIPELINE_TEMPLATE_DELETE_ROUTE,
  PIPELINE_TEMPLATE_GET_BY_ID_ROUTE: PIPELINE_TEMPLATE_GET_BY_ID_ROUTE,
  PIPELINE_TEMPLATE_GET_ROUTE: PIPELINE_TEMPLATE_GET_ROUTE,
  PIPELINE_TEMPLATE_UPDATE_ROUTE: PIPELINE_TEMPLATE_UPDATE_ROUTE,
  RESET_PASSWORD_ROUTE: RESET_PASSWORD_ROUTE,
  RESET_PASSWORD_VALIDATE_ROUTE: RESET_PASSWORD_VALIDATE_ROUTE,
  SESSION_CREATE_ACCOUNT_ROUTE: SESSION_CREATE_ACCOUNT_ROUTE,
  SESSION_CREATE_TENANT_ROUTE: SESSION_CREATE_TENANT_ROUTE,
  SESSION_GET_ACCOUNTS_META_ROUTE: SESSION_GET_ACCOUNTS_META_ROUTE,
  SESSION_LINK_ACCOUNT_ROUTE: SESSION_LINK_ACCOUNT_ROUTE,
  SESSION_LIST_ROUTE: SESSION_LIST_ROUTE,
  SESSION_REMOVE_ACCOUNT_ROUTE: SESSION_REMOVE_ACCOUNT_ROUTE,
  SESSION_REVOKE_ALL_ROUTE: SESSION_REVOKE_ALL_ROUTE,
  SESSION_REVOKE_ROUTE: SESSION_REVOKE_ROUTE,
  SESSION_SWITCH_ACCOUNT_ROUTE: SESSION_SWITCH_ACCOUNT_ROUTE,
  SESSION_SWITCH_TENANT_ROUTE: SESSION_SWITCH_TENANT_ROUTE,
  SIGN_IN_ROUTE: SIGN_IN_ROUTE,
  SIGN_OUT_ROUTE: SIGN_OUT_ROUTE,
  SIGN_UP_ROUTE: SIGN_UP_ROUTE,
  STEP_GET_ROUTE: STEP_GET_ROUTE,
  STEP_TEMPLATE_CREATE_ROUTE: STEP_TEMPLATE_CREATE_ROUTE,
  STEP_TEMPLATE_DELETE_ROUTE: STEP_TEMPLATE_DELETE_ROUTE,
  STEP_TEMPLATE_GET_BY_ID_ROUTE: STEP_TEMPLATE_GET_BY_ID_ROUTE,
  STEP_TEMPLATE_GET_ROUTE: STEP_TEMPLATE_GET_ROUTE,
  STEP_TEMPLATE_UPDATE_ROUTE: STEP_TEMPLATE_UPDATE_ROUTE,
  TENANT_CREATE_ROUTE: TENANT_CREATE_ROUTE,
  TENANT_DELETE_ROUTE: TENANT_DELETE_ROUTE,
  TENANT_GET_BY_ID_ROUTE: TENANT_GET_BY_ID_ROUTE,
  TENANT_GET_ROUTE: TENANT_GET_ROUTE,
  TENANT_INVITE_USERS_ROUTE: TENANT_INVITE_USERS_ROUTE,
  TENANT_UPDATE_ROUTE: TENANT_UPDATE_ROUTE,
  USER_CREATE_ROUTE: USER_CREATE_ROUTE,
  USER_DELETE_ROUTE: USER_DELETE_ROUTE,
  USER_GET_BY_ID_ROUTE: USER_GET_BY_ID_ROUTE,
  VALIDATE_SESSION_ROUTE: VALIDATE_SESSION_ROUTE,
};
